# Generated by Django 4.2.5 on 2023-10-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultorio',
            table='consultorio',
        ),
    ]
